### PR TITLE
added dask exploration notebook

### PR DESCRIPTION
**Pull request by meiertgrootes**

### CODE REVIEW

**Comment by meiertgrootes** [comment]
HI @rogerkuou  PR is open. Have a look and let me know if anything is unclear.

**Comment by rogerkuou** [comment]
Thanks @meiertgrootes ! I think the example with the two joblib clients are quite clear already.
Just one small check: you also show an example on calling joblib client on a Dask Array, but the array was not defined. Just to make sure that there is no accidental deleting cell. The example is already clear as it is.

**Comment by meiertgrootes** [comment]
Hi @rogerkuou,

the dask array example is undefined, and just meant to show the syntax usage. I was am/looking at deployment of multiple LocalCluster on a system to also demo publishing of datasets, but think that isn't necessary for the question at hand.

**Comment by rogerkuou** [comment]
Sure! I will merge this PR then and organize the current notebooks we have. I will let you know the new location of this example.

**Pull request merged**
